#!/bin/bash

#ecut_list='40 50 60'
ecut_list='30 40 50 60 70 80'
k_list='2 4 6 8'
#k_list='2 3 4 5 10 15 20 25 30'

for ecut in $ecut_list
do
   for k in $k_list
   do
      fname="$ecut.$k"
      scf_name="CdS.scf.$fname" # file name
      #echo $fname
      mkdir $fname
      cd $fname
      cp ../Cd.pbesol-dn-rrkjus_psl.0.3.1.UPF .
      cp ../s_pbesol_v1.4.uspp.F.UPF .
      #cp Cd.pbesol-dn-rrkjus_psl.0.3.1.UPF $fname
      #cp s_pbesol_v1.4.uspp.F.UPF $fname
      cat > $scf_name.in << EOF
&control
    calculation   ='scf'
    restart_mode  ='from_scratch',
    outdir        = "./"
    prefix        = "$PREFIX "
    pseudo_dir    = "./"
    
 /
 &system
    a           =  5.82
    ecutwfc     =  $ecut
    ibrav       =  1
    nat         =  8
    ntyp        =  2
    
 /
 &electrons
    conv_thr         =  1.00000e-03
    electron_maxstep =  200
    mixing_beta      =  7.00000e-01
    startingpot      = "atomic"
    startingwfc      = "atomic+random"
/

ATOMIC_SPECIES
Cd    112.41100 Cd.pbesol-dn-rrkjus_psl.0.3.1.UPF 
S      32.06600 s_pbesol_v1.4.uspp.F.UPF

ATOMIC_POSITIONS {angstrom}
Cd      0.000000   0.000000   0.000000
Cd      0.000000   2.909000   2.909000
Cd      2.909000   0.000000   2.909000
Cd      2.909000   2.909000   0.000000
S       1.454500   1.454500   1.454500
S       1.454500   4.363500   4.363500
S       4.363500   1.454500   4.363500
S       4.363500   4.363500   1.454500
K_POINTS  {automatic}
$k $k $k 0 0 0
EOF

    mpirun -np 4 pw.x < $scf_name.in > $scf_name.out

      rm -rf sil.*

      cd ../
tot_en=`grep "!    total energy" ${fname}/${scf_name}.out | awk '{printf "%15.12f\n",$5}'`

echo "$k  $tot_en" >> k_mesh_conv_$ecut
echo "$ecut $tot_en" >> ecut_conv_$k-$k-$k
   done # k
done # ecut
